# Generated by Django 3.2.8 on 2021-10-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_start',
            field=models.DateField(auto_now=True),
        ),
    ]
