# Generated by Django 3.2 on 2021-12-05 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='user_id',
        ),
    ]
