# Generated by Django 3.1.5 on 2021-11-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentquestion',
            name='answer',
            field=models.TextField(default='', null=True),
        ),
    ]
