# Generated by Django 3.2.8 on 2021-10-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_course_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_end',
            field=models.DateField(auto_now=True),
        ),
    ]
