# Generated by Django 3.1.5 on 2021-11-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211122_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentquestion',
            name='type',
            field=models.TextField(choices=[('PA', 'Paragraph'), ('MC', 'Multiple choice'), ('CB', 'Check box')], default='PA'),
        ),
    ]
