# Generated by Django 3.2 on 2022-01-02 12:21

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_expandeduser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='expandeduser',
            managers=[
                ('objects', api.models.ExpandedUserManager()),
            ],
        ),
    ]
