# Generated by Django 3.1.5 on 2021-11-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_assignmentquestion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentquestion',
            name='answer',
            field=models.TextField(default=''),
        ),
    ]
