# Generated by Django 3.2 on 2021-11-21 06:07

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_course_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(default='posts/default.jpg', upload_to=api.models.upload_to, verbose_name='Image'),
        ),
    ]
