# Generated by Django 3.2 on 2022-01-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_expandeduser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentanswer',
            name='answer',
            field=models.TextField(default='', null=True),
        ),
    ]
