# Generated by Django 3.2 on 2021-11-21 07:04

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_course_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
    ]
