# Generated by Django 3.1.5 on 2021-11-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_assignmentquestion_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentform',
            old_name='Lecturer_id',
            new_name='lecturer_id',
        ),
    ]
