# Generated by Django 3.2 on 2022-01-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_assignmentanswer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='expandeduser',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='expandeduser',
            name='job',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
