# Generated by Django 3.2 on 2021-11-22 09:10

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_course_course_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(default='one.png', upload_to=api.models.upload_to, verbose_name='Image'),
        ),
    ]
