# Generated by Django 3.2 on 2022-01-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220107_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='expandeduser',
            name='biography',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
