# Generated by Django 3.2 on 2022-01-08 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_expandeduser_biography'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expandeduser',
            old_name='biography',
            new_name='hobby',
        ),
    ]
