# Generated by Django 3.2 on 2021-11-22 09:18

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_course_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(default='course/one.jpg', null=True, upload_to=api.models.upload_to, verbose_name='Image'),
        ),
    ]
