# Generated by Django 3.2 on 2022-01-08 10:47

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('api', '0008_rename_biography_expandeduser_hobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='expandeduser',
            name='interest_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
