# Generated by Django 3.2 on 2022-01-09 06:27

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_expandeduser_interest_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='expandeduser',
            name='profile_image',
            field=models.ImageField(default='user/default.jifif', null=True, upload_to=api.models.profile_upload_to, verbose_name='Image'),
        ),
    ]
