# Generated by Django 3.2 on 2022-01-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_task'),
        ('api', '0009_course_students'),
    ]

    operations = [
    ]
