# Generated by Django 3.2 on 2022-01-09 06:29

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_expandeduser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expandeduser',
            name='profile_image',
            field=models.ImageField(default='user/default.jfif', null=True, upload_to=api.models.profile_upload_to, verbose_name='Image'),
        ),
    ]
