# Generated by Django 3.2 on 2021-11-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_course_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date_end',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_start',
            field=models.DateField(auto_now=True),
        ),
    ]
