# Generated by Django 3.2 on 2021-11-28 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211123_1250'),
        ('api', '0012_auto_20211128_1755'),
    ]

    operations = [
    ]
