# Generated by Django 3.2 on 2021-11-28 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_0002_auto_20211123_1250_0012_auto_20211128_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='lesson',
            new_name='lesson_id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='student',
            new_name='student_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_name',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='course description text'),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='course_name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignmentanswer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='assignmentform',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='assignmentquestion',
            name='assignment_form_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_questions', to='api.assignmentform'),
        ),
        migrations.AlterField(
            model_name='assignmentquestion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='expandeduser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
