# Generated by Django 3.2 on 2022-01-06 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('posttxt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='discuss.posttxt')),
                ('comment_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='discuss.comment')),
            ],
            bases=('discuss.posttxt',),
        ),
    ]
